### ISSUE TITLE
Deiver Cortez | PT-course-18-19

### ISSUE THREAD

**Issue by deinca** [cmda-bt/pt-course-18-19#1]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Deiver Zamora Cortez`

## Class
`TECH 2`

## About me
`Geboren in Bolivia en ben sinds mijn 9de in Nederland  en ik hou van Muziek produceren`

## Goals
`Beter worden in JavaScript`

## Skill level
`Intermediate`

## GitHub username
[Deiver Cortez](https://github.com/Loquino)

## GitHub repository
[Project Repository Deiver Cortez](https://github.com/Loquino/pt-course-18-19)

**Comment by dandevri** [comment]
Can you re-open this issue in the JS bootcamp repo?

https://github.com/cmda-bt/js-bootcamp-18-19/issues?
