### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by RooyyDoe** [cmda-bt/pt-course-18-19#10]
# Octocat

## Name
`Roy Kuijper`

## Class
`211`

## GitHub username
`https://github.com/RooyyDoe/`

## I Closed PR
`https://github.com/RooyyDoe/github-slideshow/pull/3#`

## II GitHub Pages
`https://rooyydoe.github.io/github-pages-with-jekyll/`

**Comment by dandevri** [comment]
Looking good!
