### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by nlvo** [cmda-bt/pt-course-18-19#11]
# Octocat

## Name
Lien Vo

## Class
Tech 2 | 207

## GitHub username
[nlvo](https://github.com/nlvo
)
## I Closed PR
[closed PR](https://github.com/nlvo/github-slideshow/pull/3
)
## II GitHub Pages
[github pages](https://nlvo.github.io/github-pages-with-jekyll/)

**Comment by dandevri** [comment]
Looking good!
