### ISSUE TITLE
Project Tech Kaan

### ISSUE THREAD

**Issue by cenikk** [cmda-bt/pt-course-18-19#12]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Kaan Cenik

## Class
204

## About me
I like coding with HTML, CSS and JS

## Goals
Extend my skills in coding

## Skill level
intermediate

## GitHub username
https://github.com/cenikk

## GitHub repository
https://github.com/cenikk/project-tech

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
