### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Sanderoost** [cmda-bt/pt-course-18-19#13]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Sander Oostenbrink

## Class
Klas 209

## About me
23 Years old and currently living in Castricum

## Goals
Learn more about programming in javascript

## Skill level
Intermediate

## GitHub username
https://github.com/Sanderoost

## GitHub repository
https://github.com/Sanderoost/blok-tech

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
