### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by MartijnKeesmaat** [cmda-bt/pt-course-18-19#14]
# My Introduction

## Name
Martijn Keesmaat

## Class
208 || tech 2

## About me
Aspiring creative developer, freelance designer/front-end

## Goals
- Understanding the principles of JS better
- Write better, cleaner and more scale-able code

## Skill level
intermediate || advanced

## GitHub username
[MartijnKeesmaat](https://github.com/MartijnKeesmaat)

## GitHub repository
https://github.com/MartijnKeesmaat/project-tech/wiki

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
