### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by kriskuiper** [cmda-bt/pt-course-18-19#15]
# My Introduction

## Name
`Kris Kuiper`

## Class
`Tech 1 / 209`

## About me
`I'm very passionate about modular JavaScript and CSS`

## Goals
`To get better at writing clean JavaScript and learn the basics of NodeJS.`

## Skill level
`Probably between intermediate and advanced`

## GitHub username
[kriskuiper](https://github.com/kriskuiper)

## GitHub repository
[Repository Project Tech](https://github.com/kriskuiper/project-tech)

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
