### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by RooyyDoe** [cmda-bt/pt-course-18-19#16]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Roy Kuijper`

## Class
`211`

## About me
`Something about me... I guess i love gaming 🎮`

## Goals
`Trying to get as much information to git guuud at programming.`

## Skill level
`beginner - intermediate (Inbetween)`

## GitHub username
`https://github.com/RooyyDoe`

## GitHub repository
`https://github.com/RooyyDoe/project-tech/wiki`

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
