### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Kuckelkorn** [cmda-bt/pt-course-18-19#17]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Remco Kuckelkorn

## Class
201

## About me
The forever student

## Goals
Make a working site with the skills I've learned in the last 10 weeks 

## Skill level
Beginner in JS

## GitHub username
https://github.com/Kuckelkorn

## GitHub repository
https://github.com/Kuckelkorn/Assignment-Project-Tech

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
