### ISSUE TITLE
Wiki Sajjad Ali

### ISSUE THREAD

**Issue by Sajjad0405** [cmda-bt/pt-course-18-19#18]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Sajjad Ali

## Class
Klas 202

## About me
Hardwerkend 👍 

## Goals
Betere grip krijgen op javascript 

## Skill level
Best wel een beginner. Heb er nu nog veel moiete mee

## GitHub username
https://github.com/Sajjad0405

## GitHub repository
https://github.com/Sajjad0405/Project-tech/wiki

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.

But, I assume you are going to be working in: https://github.com/Sajjad0405/dating-app
