### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Kalemis** [cmda-bt/pt-course-18-19#19]
# My Introduction

## Name
Artemis Kalemis

## Class
bt-1

## About me
I am a 22 year old student living in Amsterdam with my boyfriend and my cat.

## Goals
Putting my new knowledge into practice.

## Skill level
Beginner

## GitHub username
[My github page](https://github.com/Kalemis)

## GitHub repository
[Repository](https://github.com/Kalemis/project-tech)

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
