### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by victorlaforga** [cmda-bt/pt-course-18-19#2]
# My Introduction

*20 jaar oud en in me vrije tijd voetbal ik vaak of ben ik met vrienden*

## Name
`Victor Laforga`

## Class
`214`

## About me
`Gewoond in Belgie, Guatemala en Nicaragua`

## Goals
`Beter worden met coderen`

## Skill level
`Beginner`

## GitHub username
'victorlaforga'

## GitHub repository

[GitHub Repository Victor](https://github.com/victorlaforga/js-bootcamp)

**Comment by dandevri** [comment]
Can you re-open this issue in the JS bootcamp repo?

https://github.com/cmda-bt/js-bootcamp-18-19/issues?
