### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by Plous01** [cmda-bt/pt-course-18-19#23]
# Octocat

## Name
Paulien

## Class
Klas 207, Project Tech

## GitHub username
Plous01

## I Closed PR
https://github.com/Plous01/github-slideshow/issues?q=is%3Aissue+is%3Aclosed

## II GitHub Pages
https://github.com/Plous01/github-slideshow

**Comment by dandevri** [comment]
Looking good! 🎉 

Any feedback on the exercise?
