### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Plous01** [cmda-bt/pt-course-18-19#24]
# My Introduction

## Name
Paulien

## Class
Klas 207, Project Tech

## About me
Ik ben erg sportief en vind het leuk om nieuwe dingen te leren.

## Goals
`Mijn skills verbeteren`

## Skill level
Beginner

## GitHub username
Plous01

## GitHub repository
https://github.com/Plous01?tab=repositories

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
