### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by nlvo** [cmda-bt/pt-course-18-19#26]
# My Introduction

## Name
Lien Vo

## Class
207 | tech 2

## About me
Junior designer/front-end developer die er ook van houd om in haar vrije tijd te tekenen.

## Goals
Het begrijpen en verbeteren van mijn Javascript skills.

## Skill level
Intermediate

## GitHub username
[nlvo](https://github.com/nlvo)

## GitHub repository
[Project Tech](https://github.com/nlvo/project-tech)

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.

But I assume you will be working in: https://github.com/nlvo/dating-app
