### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by victorlaforga** [cmda-bt/pt-course-18-19#27]
# Octocat

## Name
`Victor Laforga`

## Class
`214`

## GitHub username
[Profile](https://github.com/victorlaforga)

## I Closed PR
[Closed PR](https://github.com/victorlaforga/github-slideshow/issues/2)

## II GitHub Pages
[Pages with jekyll](https://victorlaforga.github.io/github-pages-with-jekyll/)

**Comment by dandevri** [comment]
Looking good! 🎉 

Any feedback on the exercise?
