### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by GiovanniDw** [cmda-bt/pt-course-18-19#28]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Giovanni`

## Class
`207`

## About me
`-`

## Goals
`Being better than my previous self =D`

## Skill level
`Beginner`

## GitHub username
[GiovanniDw](https://github.com/GiovanniDw)

## GitHub repository
[pt-course](https://github.com/GiovanniDw/pt-course)

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
