### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by kriskuiper** [cmda-bt/pt-course-18-19#3]
# Octocat

## Name
Kris Kuiper

## Class
209 / Tech 1

## GitHub username
https://github.com/kriskuiper

## I Closed PR
https://github.com/kriskuiper/github-slideshow/pull/3

## II GitHub Pages
https://kriskuiper.github.io/github-slideshow/#/

## My thoughts
Really liked the exercise, already wanted to learn how to use Git via the command line. Now I know the basics.

Had some issues with two factor authentication, Git gave me some errors on my username and password... Fixed it together with Thijs 😄.

**Comment by kriskuiper** [comment]
The right link to the GitHub pages exercise: https://kriskuiper.github.io/github-pages-with-jekyll/

**Comment by dandevri** [comment]
Looking good!

Had the same Git struggles while live demoing today 🙃 That's why you need to prepare those things.
