### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by RowinVanAmsterdam** [cmda-bt/pt-course-18-19#30]
# My Introduction

## Name
Rowin

## Class
Bt-1

## About me
Love to work on my car

## Goals
Expend my knowledge

## Skill level
Beginner

## GitHub username
Rowin206

## GitHub repository
https://github.com/Rowin206/DatingApp

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.

But, I assume you will be working in: https://github.com/Rowin206/DatingApp

**Comment by RowinVanAmsterdam** [comment]
oops, my mistake. You're right, I will work in the DatingApp repo. I changed it.
