### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by qiubee** [cmda-bt/pt-course-18-19#32]
# My Introduction

👋

## Name
kevin

## Class
214

## About me
:earth_africa: `11111100011`  :computer: :art: :triangular_ruler:

## Goals
Increase my knowledge

## Skill level
`beginner`

## GitHub username
[qiubee](https://github.com/qiubee)

## GitHub repository
[Lets Date](https://github.com/qiubee/lets-date)

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.

Your repo does feel kinda lonely...
