### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by qiubee** [cmda-bt/pt-course-18-19#33]
# Octocat
:octocat:

## Name
kevin

## Class
214

## GitHub username
[qiubee](https://github.com/qiubee)

## I Closed PR
[Closed *Pull request*](https://github.com/qiubee/github-slideshow/pull/3)

## II GitHub Pages
[Ntng - Just a website of nothing](https://qiubee.github.io/github-pages-with-jekyll)

**Comment by dandevri** [comment]
Looking good! 🎉 

Any feedback on the exercise?
