### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by Sajjad0405** [cmda-bt/pt-course-18-19#36]
# Run

## Name
`Sajjad Ali`

## Class
`202`

## GitHub username
https://github.com/Sajjad0405/Project-tech/wiki/Week2---Branding-research-&-job-stories

Dit is een issue voor het nakijken van de job story.

**Comment by dandevri** [comment]
This isn't the run exercise. I will check the Job Stories in the repository you handed in in the introduction issue.
