### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by GiovanniDw** [cmda-bt/pt-course-18-19#38]
# Octocat

## Name
`Giovanni`

## Class
`207`

## GitHub username
[GiovanniDw](https://github.com/GiovanniDw)

## I Closed PR

[Link to the closed PR from the Introduction to GitHub exercise](https://github.com/GiovanniDw/github-slideshow/pull/3)

## II GitHub Pages
[`Link to the GitHub Pages website`](https://giovannidw.github.io/github-pages-with-jekyll/)

**Comment by dandevri** [comment]
Looking good! 🎉 

Any feedback on the exercise?
