### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by Chazzers** [cmda-bt/pt-course-18-19#40]
# Octocat

## Name
`Chazz Mannering`

## Class
`210`

## GitHub username
[Chazzers](https://github.com/Chazzers)

## I Closed PR
[https://github.com/Chazzers/project-tech/wiki/1.-Competetive-Analysis-1.0](https://github.com/Chazzers/project-tech/wiki/1.-Competetive-Analysis-1.0)

**Comment by dandevri** [comment]
This isn't a link to the octocat exercise?
