### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Kalemis** [cmda-bt/pt-course-18-19#41]
# Config

## Name
Artemis

## Class
bt-1

## GitHub username
[Kalemis](https://github.com/Kalemis)

## GitHub repository
[Project tech](https://github.com/Kalemis/project-tech)

## Summary
I created 3 pull requests for 3 different classmates for last weeks assignment. 
- In one repository I noticed that the engine setup in the index.js file could be made a lot simpler by only adding app. one time at the top, instead for each line.
- The second pull request was for a simple mistake by allowing text input in a field where it should only accept numbers (age). 
- The last pull request was about the tail partial which wasn't in the partials folder. 

I actually didn't find it very difficult to spot these very small mistakes. I think it is very easy to overlook something when you're that focussed on it.

**Comment by dandevri** [comment]
Hi Artemis!

* Can you elleborate more on the extensions and linters you've added to your project?
* Can you add the configuration files, linters and rules to your wiki? What choices did you make?

The pull requests are the assignment for next week, can fill in the `teamwork` issue with the three pull requests you've made?

Thanks! 🎉
