### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by RowinVanAmsterdam** [cmda-bt/pt-course-18-19#42]
# Config

## Name
Rowin

## Class
bt-1

## GitHub username
https://github.com/Rowin206

## GitHub repository
https://github.com/Rowin206/DatingApp

## Add a screenshot of your editor
Absolutely not! Call me boring, but I do like the standard colors actually. I can't upload an image to this? But here is a link to the screenshot: 
[screenshot](https://66.media.tumblr.com/4b41eabdc2d60ba28420f1fddc088ab2/tumblr_pofcmm7JQu1xh4pqfo1_1280.png)

## Summary
This week, I finally made my feature concrete and updated the code after the feedback. So, my code is less and much easier to read. Besides, I made three pull requests by some classmates. The feedback I did get, could also be applied by their code. So, I shared it with them as well.

**Comment by dandevri** [comment]
Boring! ;-) 

* Can you elleborate more on the extensions and linters you've added to your project?
* Can you add the configuration files, linters and rules to your wiki?

The pull requests are the assignment for next week, can fill in the `teamwork` issue with the three pull requests you've made?

Thanks! 🎉
