### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Sajjad0405** [cmda-bt/pt-course-18-19#43]
# Config

## Name
Sajjad Ali

## Class
202

## GitHub username
https://github.com/Sajjad0405/

## GitHub repository
https://github.com/Sajjad0405/dating-app/

## Add a screenshot of your editor
`Does it look fancy?`

## Summary
Er is deze week veel gebeurd. Ten eerste ben ik overgestapt van brackets naar vscode. Niet omdat brackets niet goed genoeg was, maar vscode ben ik begonnen te gebruiken omdat ik via de code editor ook de terminal kan gebruiken, en dit is heel handig. 
Daarnaast heb ik mijn job story geupdated en al begonnen met de week opdracht van backend en frontend.

**Comment by dandevri** [comment]
Hi Sajjad!

* Can you elleborate more on the extensions and linters you've added to your project? 
* I don't see any screenshots of your editor?
* Can you add the configuration files, linters and rules to your wiki? What choices did you make?

Make sure you also decide if you go dutch or english.

Thanks! 🎉
