### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by StefanGerrits2** [cmda-bt/pt-course-18-19#44]
# Config

## Name
`Stefan Gerrits`

## Class
`211 - Tech 1`

## GitHub username
[My account](https://github.com/StefanGerrits2)

## GitHub repository
[My repo](https://github.com/StefanGerrits2/datingwebsite-bloktech)

## Add a screenshot of your editor
![](http://i63.tinypic.com/30lo4e1.png)

Fancy right?

#### Er zit een terminal in VS Code

Dit is naar mijn mening erg handig. Hierdoor hoef ik niet in een apart opdrachtprompt elke keer te navigeren naar mijn map om vervolgens een commando uit te voeren.

#### Je kan makkelijker de kleuren aanpassen in VS Code

Doordat er vele thema's zijn in VS Code kan ik mijn code de kleuren geven die ik prettig vind. Op Brackets was dit vrij minimaal.

#### Over het algemeen is er meer te vinden over VS Code; bijvoorbeeld extensies, kleurenschema's etc

Naar mijn idee is VS Code ook populairder waardoor er meer te vinden is zoals veel meer extensies.

#### Je kan een extensie gebruiken om je code in het klein te zien om zo makkelijker te kunnen navigeren in je code editor.

Als ik erg lange code heb en ik zoek naar iets kan ik dan deze extensie gebruiken zodat ik gemakkelijker door mijn code kan navigeren.

#### Ik vind het overzicht van je bestanden links ook veel beter dan Brackets. 

Op mijn screenshot zie je bijvoorbeeld dat elk soort bestand een apart icoontje heeft wat het mij makkelijker maakt om zo het verschil te zien. 

### Linters die ik heb geïnstalleerd

* ESLint
* CSSLint
* HTMLHint

Ze helpen me allemaal met dingen zoals:

* Als ik een haakje ben vergeten te openen of sluiten
* Verschillende tabs of spatie gebruik
* Als ik iets vergeet te declareren, of als iets al is gedeclareerd
* Als iets onverwachts gebeurd in de code zoals een random haakje in een stuk code

**Comment by dandevri** [comment]
Hi Stefan!

Your editor doesn't look that fancy! ;-)

* Nice job on investigating the different linters, can you add those to your wiki?
* Good arguments for switching to code, make sure you also add those to your wiki.

Thanks! 🎉
