### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by cenikk** [cmda-bt/pt-course-18-19#46]
# Config

## Name
Kaan Cenik

## Class
204

## GitHub username
https://github.com/cenikk

## GitHub repository
https://github.com/cenikk/datingapp

## Add a screenshot of your editor
![Visual Studio Code](https://github.com/cenikk/project-tech/blob/master/assets/code-editor.png)

## Summary
I've installed multiple new extensions in my code-editor, I got a few new handy ones while in class when we had to compare the extensions we used with each other. Additionally, I've also learned what a Linter does and why it can be very useful to have one installed and configured to your own preferences. You can find the whole documentation on which editor and extensions I use in my Wiki page (dating-app).

**Comment by dandevri** [comment]
Hi Kaan!

The wiki looks good! Can you expand more on the different linters you've setup in your project? I see a lot about your code editor, but not much about your linters and configs.

Thanks! 🎉

**Comment by cenikk** [comment]
Yes I can. Thanks for the feedback! 😀

**Comment by cenikk** [comment]
Hey, I've added a full [page about Linting](https://github.com/cenikk/datingapp/wiki/3.3-Linter) in my wiki.

**Comment by dandevri** [comment]
Nice! 👍
