### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by nlvo** [cmda-bt/pt-course-18-19#47]
# Config

## Name
Lien Vo

## Class
Tech 1 | 207

## GitHub username
[nlvo](https://github.com/nlvo/)

## GitHub repository
[dating app repository](https://github.com/nlvo/dating-app/)

## Add a screenshot of your editor
<img width="1440" alt="vscode-theme" src="https://user-images.githubusercontent.com/8554238/54475430-8e346680-47f1-11e9-8c22-78e95c227304.png">

## Summary
At the moment I'm trying vscode, so far so good. I used to use sublime, so there shortcuts aren't that different, which makes it a bit easier to use.

- material theme
- eslint
- beautify

Compared to sublime I didn't need to install as many extensions as I thought, a lot of it existed already in vscode. But I'll probably add more down the road.

[Wiki](https://github.com/nlvo/dating-app/wiki)

**Comment by dandevri** [comment]
Hi Lien!

Wow, cool colors 😎 

* Can you elleborate more on the extensions and linters you've added to your project? Make sure you add those to your wiki.
* Can you add the configuration files, linters and rules to your wiki? What choices did you make?

Thanks! 🎉
