### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by victorlaforga** [cmda-bt/pt-course-18-19#48]
# Config

## Name
`Victor Laforga`

## Class
`Tech`

## GitHub username
[https://github.com/victorlaforga](https://github.com/victorlaforga)

## GitHub repository
[https://github.com/victorlaforga/project-tech](https://github.com/victorlaforga/project-tech)

## Add a screenshot of your editor

![screenshot my atom](https://user-images.githubusercontent.com/37700441/54478086-db730100-480e-11e9-90d6-c4ebf0f59a4d.png)

## Summary
`In this week i switched from brackets to atom. The reason I did this was because atom had a lot of plugins (and themes), but also it has a very good git integration. I have chosen my theme and installed several plugins like eslint, color-picker, beautify etc.`

**Comment by dandevri** [comment]
Hi Victor!

Looking good! 😎 

* Can you elleborate more on the extensions and linters you've added to your project?
* Can you add the configuration files, linters and rules to your wiki? What choices did you make?

I don't see a lot of documentation on your wiki page. Try to tell why you've chosen for this setup.
