### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by GiovanniDw** [cmda-bt/pt-course-18-19#49]
# Config

## Name
`Giovanni`

## Class
`207`

## GitHub username
[GiovanniDw](https://github.com/GiovanniDw)

## GitHub repository
[pt-course](https://github.com/GiovanniDw/pt-course)

## Add a screenshot of your editor
![`Does it look fancy?`](

![](https://raw.githubusercontent.com/GiovanniDw/pt-course/master/assets/myvscode.png)
)

## Summary
Already knew some linters, tried some other plugin than weren't for me, like file icons, and other themes. I'm a little behind schedule, trying to fix that, but can't see the woods because of the trees sometimes.

**Comment by dandevri** [comment]
Hi Giovanni,

Looking good! 😎 

* Can you elleborate more on the extensions and linters you've added to your project?
* Can you add the configuration files, linters and rules to your wiki? What choices did you make?

Make sure you also tell why you've chosen these linters and configs. Document those in your wiki, I don't see a lot there.
