### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by MartijnKeesmaat** [cmda-bt/pt-course-18-19#5]
# Octocat

## Name
Martijn Keesmaat

## Class
208 || tech 2

## GitHub username
https://github.com/MartijnKeesmaat

## I Closed PR
https://github.com/MartijnKeesmaat/github-slideshow/pull/3

## II GitHub Pages
https://martijnkeesmaat.github.io/github-pages-with-jekyll/

**Comment by dandevri** [comment]
Looking good!
