### ISSUE TITLE
Teamwork

### ISSUE THREAD

**Issue by RowinVanAmsterdam** [cmda-bt/pt-course-18-19#50]
# Config

## Name
Rowin

## Class
bt-1

## GitHub username
Rowin206

## GitHub repository
https://github.com/Rowin206/DatingApp

## Summary
I did make some pull requests bij 3 classmates, you'll find them here: 
Kalemis: https://github.com/Kalemis/Assignments/pull/1
Cenikk: https://github.com/cenikk/datingapp/pull/1
Sajjad0405: https://github.com/Sajjad0405/dating-app/pull/5

**Comment by dandevri** [comment]
Looks good!
