### ISSUE TITLE
Teamwork

### ISSUE THREAD

**Issue by cenikk** [cmda-bt/pt-course-18-19#51]
# Config

## Name
Kaan Cenik

## Class
204

## GitHub username
https://github.com/cenikk

## GitHub repository
https://github.com/cenikk/datingapp

## Summary
I went through some classmates' code and see if I could spot anything that shouldn't be there. This could either be a Syntax-error or a Stylistic-error.  
By one of my classmate I told them to make a consistent use of semicolons in his code, since he'd sometimes not use it and sometimes he would. I also gave him a tip to use a linter in occasions like this.  
By another classmate I spotted a syntax-error where the code wouldn't push data to a "data" array. I helped fixing this.  
Last of all, I helped a classmate having a good file/folder structure. For example, he had his tail.ejs in his views folder while he also had a partials folder. I recommended him putting the tail.ejs inside of there.

**Comment by cenikk** [comment]
The week 5 - Teamwork issue gets stored as Config whenever you click on it. Had to change the title to Teamwork myself.

**Comment by dandevri** [comment]
Did you make pull requests into those repositories?

Will fix the GitHub issue, thanks for the heads up!

**Comment by cenikk** [comment]
Sure did, I should've probably added links to their repo, so my excuses for that.
These are the links:
- [Rowin206](https://github.com/Rowin206/DatingApp)
- [Kalemis](https://github.com/Kalemis/Assignments)
- [Sajjad0405](https://github.com/Sajjad0405/dating-app)
