### ISSUE TITLE
Teamwork

### ISSUE THREAD

**Issue by nlvo** [cmda-bt/pt-course-18-19#52]
# Config

## Name
Lien Vo

## Class
Tech 2 | 207

## GitHub username
[Nlvo](https://github.com/nlvo/)

## GitHub repository
[Dating app](https://github.com/nlvo/dating-app)

## Summary
I created 2 pull request, still have to do one more. Where I either cleaned up the file a bit or rewrote a piece of code.
1. [Gio](https://github.com/GiovanniDw/pt-course/pull/3)
2. [Paulien](https://github.com/Plous01/ProjectTech/pull/9)

**Comment by dandevri** [comment]
Looks good!
