### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by robert-hoekstra** [cmda-bt/pt-course-18-19#53]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Robert Hoekstra`

## Class
`CMD214`

## About me
`26 year old barista aiming to become a ux-designer`

## Goals
`=To get a better understanding of back-end languages. To make better products and prototypes`

## Skill level
`Beginner`

## GitHub username
`https://github.com/robert-hoekstra`

## GitHub repository
`https://github.com/robert-hoekstra/BlokTech`

**Comment by dandevri** [comment]
👋  Robert, I've added your wiki to our _project-tech_ admin sheet!

**Comment by robert-hoekstra** [comment]
Great!
