### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by VinceKaars** [cmda-bt/pt-course-18-19#54]
# My Introduction

## Name
Vince Kaars

## Class
FDMCI_TECH 4

## About me
21 year old Dutchie living in the small city of Edam. 

## Goals
To graduate this year.

## Skill level
Beginner

## GitHub username
[https://github.com/VinceKaars](url)

**Comment by VinceKaars** [comment]
Wiki: https://github.com/VinceKaars/TECH2019

**Comment by dandevri** [comment]
👋  Vince, I've added your wiki to our _project-tech_ admin sheet!
