### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Dejorden94** [cmda-bt/pt-course-18-19#55]
# Introduction Dejorden

## Name
Dejorden Moerman

## Class
212

## About me
Second year communication and multimedia student, mostly interested in tech side of things and design ethics.

## Goals
Learning how to collaborate with other people on a development project and bringing my skills in html, css and javascript to the next level. Also getting more comfortable with the backend side of things. 

## Skill level
intermediate

## GitHub username
https://github.com/Dejorden94

## GitHub repository
https://github.com/Dejorden94/Project-tech-datingapp

**Comment by dandevri** [comment]
👋  Dejorden, this link points to your bootcamp repo.
