### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Aidan98** [cmda-bt/pt-course-18-19#56]
# My Introduction

## Name
Aidan K. Omwando

## Class
Tech 3

## About me
Likes world of warships, beer & pizza

## Goals
Learn how to make animations using javascript and or CSS

## Skill level
Intermediate

## GitHub username
Aidan98

## GitHub repository
https://github.com/Aidan98/Project-Tech.git

**Comment by dandevri** [comment]
👋  Aidan, I've added your wiki to our _project-tech_ admin sheet!
