### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by StephanKop** [cmda-bt/pt-course-18-19#57]
# My Introduction

## Name
Stephan Kop 

## Class
Tech 3

## About me
following this course for the second time because i failed last year. 
I'm mainly a front-end developer with the ambition to learn more about backend development. Also created an app using react-native during my internship.

## Goals
Learning more about integrating databases within my projects.

## Skill level
frontend: intermediate. backend: beginner

## GitHub username
superstephan1

## GitHub repository
https://github.com/superstephan1/Project-Tech

**Comment by dandevri** [comment]
👋  Stephan, I've added your wiki to our _project-tech_ admin sheet!

Can you send me your @hva mail and student nummer on slack? You were not on the classlist.
