### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by StephanKop** [cmda-bt/pt-course-18-19#58]
# Octocat

## Name
Stephan Kop

## Class
Tech 3

## GitHub username
Superstephan1

## I Closed PR
https://github.com/superstephan1/github-slideshow/pull/3

## II GitHub Pages
https://superstephan1.github.io/github-pages-with-jekyll/

**Comment by dandevri** [comment]
👋  Hi Stephan,

Looking good! How did it go? Any feedback on the assignment?
