### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by Ramon96** [cmda-bt/pt-course-18-19#60]
# Octocat

## Name
Ramon

## Class
Tech 3

## GitHub username
Ramon96

## I Closed PR
[Closed PR](https://github.com/Ramon96/github-slideshow/pull/3)

## II GitHub Pages
[Github Pages](https://ramon96.github.io/github-pages-with-jekyll/)

**Comment by Ramon96** [comment]
The assignment says you have to do "[GitHub Pages from the Command Line](https://services.github.com/on-demand/github-cli/)", but when I follow the link the assignment is no where to be found. I do find a Github pages exercise but that one is without the command line. So I might have done the wrong exercise. could have been [this](https://help.github.com/en/articles/creating-project-pages-using-the-command-line) one. It was a little bit confusing. Exercises were fun :)

**Comment by dandevri** [comment]
👋 Hi Ramon,

Looking good! How did it go?

You are right, wrong link in this week's markdown file, I've updated the link to the correct assignment.
