### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by ccdejene** [cmda-bt/pt-course-18-19#61]
# My Introduction

## Name
`Eyob Westerink`

## Class
TECH3

## About me
I like to design and develop websites.
I have worked as a front-end developer for various companies and I have established a online sneakerplatform.

## Goals
Expand knowledge

## Skill level
Intermediate / advanced

## GitHub username
`https://github.com/EyobDejene`

## GitHub repository
`https://github.com/EyobDejene/projectTech`

**Comment by dandevri** [comment]
👋  Eyob, I've added your wiki to our _project-tech_ admin sheet!
