### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by smithr002** [cmda-bt/pt-course-18-19#62]
# My Introduction

## Name
Robyn Smith

## Class
Tech 3

## About me
I love spending time with friends

## Goals
I really want to learn how to work with node.js

## Skill level
beginner

## GitHub username
smithr002

## GitHub repository
https://github.com/smithr002/Project-Tech.git

**Comment by dandevri** [comment]
👋  Robyn, I've added your wiki to our _project-tech_ admin sheet!
