### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by woutarb** [cmda-bt/pt-course-18-19#63]
# My Introduction

## Name
Wouter Bijnsdorp

## Class
Tech 3

## About me
Metalhead, tabletoprpg, book, comic en videogame nerd.

## Goals
Creating a feature by myself by designing and coding it.

## Skill level
Beginner

## GitHub username
https://github.com/wouterBijns

## GitHub repository
https://github.com/wouterBijns/ProjectTechRepo

**Comment by dandevri** [comment]
👋  Wouter, I've added your wiki to our _project-tech_ admin sheet!
