### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by woutarb** [cmda-bt/pt-course-18-19#64]
# Octocat

## Name
Wouter Bijnsdorp

## Class
Tech 3

## GitHub username
https://github.com/wouterBijns

## I Closed PR
https://github.com/wouterBijns/github-slideshow

## II GitHub Pages
https://github.com/wouterBijns/github-pages-with-jekyll

## Note
Kon "GitHub Pages from the Command Line" exercise niet vinden, daarom "github pages-with jekyll" gedaan.

**Comment by dandevri** [comment]
👋 Hi Wouter,

Looking good! How did it go?

You are right, wrong link in this week's markdown file, I've updated the link to the correct assignment.

**Comment by woutarb** [comment]
Went very well, internship experience helped quite a bit
