### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Roelmeijns** [cmda-bt/pt-course-18-19#65]
## Name
Roel Meijns

## Class
Tech 3

## Goals
Learn more about databases and how they work.

## Skill level
Beginner

## GitHub username
Roelmeijns

## GitHub repository
https://github.com/Roelmeijns/projecttech
https://github.com/Roelmeijns/projecttech/wiki

**Comment by dandevri** [comment]
👋  Roel, I've added your wiki to our _project-tech_ admin sheet!
