### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by Roelmeijns** [cmda-bt/pt-course-18-19#66]
# Octocat

## Name
Roel Meijns

## Class
Tech 3

## GitHub username
Roelmeijns

## I Closed PR
https://github.com/Roelmeijns/github-slideshow
https://github.com/Roelmeijns/github-pages-with-jekyll

## II GitHub Pages

Cant find the GitHub Pages from the Command Line exercise on https://lab.github.com/ so i did the https://github.com/Roelmeijns/github-pages-with-jekyll exercise.

**Comment by dandevri** [comment]
👋 Hi Roel,

Looking good! How did it go?

You are right, wrong link in this week's markdown file, I've updated the link to the correct assignment.
