### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by CountNick** [cmda-bt/pt-course-18-19#68]
# My Introduction

## Name
Nick

## Class
TECH3

## About me
Hi, I'm Nick student at CMD Amsterdam

## Goals
Learn more about Javascript, and learn something about backend coding.

## Skill level
Beginner/Intermediate

## GitHub username
https://github.com/CountNick

## GitHub repository
https://github.com/CountNick/Project-Tech

**Comment by dandevri** [comment]
👋  Nick, I've added your wiki to our _project-tech_ admin sheet!
