### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by charder001** [cmda-bt/pt-course-18-19#69]
# My Introduction

## Name
Rick Chardet

## Class
Tech3

## About me
Cars, Bikes, Photo, Video

## Goals
Huidige kennis checken en verbreden

## Skill level
 beginner, intermediate

## GitHub username
https://github.com/charder001

## GitHub repository
https://github.com/charder001/Project-Tech

**Comment by dandevri** [comment]
👋  Rick, I've added your wiki to our _project-tech_ admin sheet!
