### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by charder001** [cmda-bt/pt-course-18-19#70]
# Octocat

## Name
Rick Chardet

## Class
Tech3

## GitHub username
https://github.com/charder001

## I Closed PR
https://github.com/charder001/github-slideshow/pull/3

## II GitHub Pages
https://charder001.github.io/github-pages-with-jekyll/

**Comment by dandevri** [comment]
👋 Hi Rick,

Looking good! How did it go?
