### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by CountNick** [cmda-bt/pt-course-18-19#71]
# Octocat

## Name
Nick

## Class
Tech3

## GitHub username
https://github.com/countnick

## I Closed PR
https://github.com/CountNick/github-slideshow/pulls?q=is%3Apr+is%3Aclosed

## II GitHub Pages
https://countnick.github.io/github-pages-with-jekyll/

**Comment by dandevri** [comment]
👋 Hi Nick,

Looking good! How did it go?
