### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by NotAfr8Studio** [cmda-bt/pt-course-18-19#72]
# My Introduction

## Name
Mike van den Hoek

## Class
FDMCI-TECH3 (209) 

## About me
I'm someone who wants to be able to give life to my projects / designs  

## Goals
I want to learn the basics of javascript. When the course is over I'm hoping I'll be able to create my own working websites all on my own. 

## Skill level
Beginner

## GitHub username
<a href=https://github.com/Fr3akyBeakyLike> Fr3akyBeakyLike </a> 

## GitHub repository
https://github.com/Fr3akyBeakyLike?tab=repositories

**Comment by dandevri** [comment]
👋  Mike, I've added your wiki to our _project-tech_ admin sheet!
