### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by marissaverdonck** [cmda-bt/pt-course-18-19#74]
# My Introduction

## Name
Marissa Verdonck

## Class
Tech 4

## About me
Ik word ontzettend blij van skiën! Maar ook als ik een code schrijf die werkt.

## Goals
Beter worden in Javascript en werken met data.

## Skill level
Beginner, ik heb alleen de kennis van wat we bij CMD hebben geleerd.

## GitHub username
[marissaverdonck](https://github.com/marissaverdonck/BlokTech_DatingApp)

## GitHub repository
[GitHub repository](https://github.com/marissaverdonck/BlokTech_DatingApp)

**Comment by dandevri** [comment]
👋 Marissa, this link points to your bootcamp repo. It's best to create a new (separate from the bootcamp) frepository for the dating-app!

**Comment by marissaverdonck** [comment]
Hi Danny, Thanks! I changed it.

**Comment by dandevri** [comment]
Thanks! 🎉
