### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by joanpadolina** [cmda-bt/pt-course-18-19#75]
# My Introduction

## Name
Joan Padolina

## Class
Tech 4

## About me
Creatief, gemotiveerd en ik ben gek op films kijken.

## Goals
Javascript kunnen lezen begrijpen en schrijven.

## Skill level
NEWBIEE

## GitHub username
[github.com/joanpadolina](https://github.com/joanpadolina)

## GitHub repository
[Joan Padolina Repository](https://github.com/joanpadolina/ProjectTech_Jome)

**Comment by dandevri** [comment]
👋  Joan, I've added your wiki to our _project-tech_ admin sheet!
