### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Wiebsonice** [cmda-bt/pt-course-18-19#76]
# My Introduction

## Name
Wiebe Kremer

## Class
Tech 4

## About me
Im a 22 Year old CMD student, Currently working at a Rich media Ad company. Passionate football player, and fanatic sneaker collector

## Goals
I want to broaden my javascript knowledge and try to gather more knowledge about the front-end and back-end world. To make me a more complete CMD'er

## Skill level
Beginner

## GitHub username
[github.com/Wiebsonice](https://github.com/Wiebsonice/)

## GitHub repository
[GalleryMatch Repository](https://github.com/Wiebsonice/GalleryMatch)

## GitHub wiki
[GalleryMatch Wiki](https://github.com/Wiebsonice/GalleryMatch/wiki)

**Comment by dandevri** [comment]
👋  Wiebe, I've added your wiki to our _project-tech_ admin sheet!
