### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by Mokerstier** [cmda-bt/pt-course-18-19#77]
# Octocat

## Name
'Wouter van der Heijde'

## Class
'Tech-4'

## GitHub username
[My GitHub](https://github.com/Mokerstier)

## I Closed PR
[Closed PR here](https://github.com/Mokerstier/github-slideshow/pull/3)

## II GitHub Pages
[Pages through course](https://mokerstier.github.io/github-pages-with-jekyll/)

**Comment by dandevri** [comment]
👋 Hi Wouter,

Looking good! How did it go?
