### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Mokerstier** [cmda-bt/pt-course-18-19#79]
# My Introduction

## Name
Wouter van der Heijde

## Class
Tech-4

## About me
27 y/o Male living in Bigpants (Grootebroek)

## Goals
My goals for this class are getting familiar with backend and being able to set up my own database. So in the future I can create my own websites/applications from front-end to back-end.

## Skill level
intermediate

## GitHub username
[Mokerstier](https://github.com/Mokerstier)

## GitHub repository
[Repo Tech](https://github.com/Mokerstier/blokTechProject)

**Comment by dandevri** [comment]
👋 Wouter, I've added your wiki to our _project-tech_ admin sheet!
