### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by StefanGerrits2** [cmda-bt/pt-course-18-19#8]
# Octocat

## Name
`Stefan Gerrits`

## Class
`211 / Tech - 1`

## GitHub username
https://github.com/StefanGerrits2

## I Closed PR
[https://github.com/StefanGerrits2/github-slideshow/pull/3](url)

## II GitHub Pages
[https://github.com/StefanGerrits2/github-pages-with-jekyll/pull/6](url)

**Comment by dandevri** [comment]
Looking good!
