### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by robert-hoekstra** [cmda-bt/pt-course-18-19#80]
# Octocat

## Name
Robert Hoekstra

## Class
214 (Tech3)

## GitHub username
robert-hoekstra

## I Closed PR
https://github.com/robert-hoekstra/github-slideshow/pulls?q=is%3Apr+is%3Aclosed

## II GitHub Pages
https://github.com/robert-hoekstra/github-pages-with-jekyll
https://github.com/robert-hoekstra/github-pages-with-jekyll/pulls?q=is%3Apr+is%3Aclosed

I get the basics of github. However I have a feeling that I will get more used to it by simply working more with it.

**Comment by robert-hoekstra** [comment]
https://robert-hoekstra.github.io/github-pages-with-jekyll/ < the actual link to the published page

**Comment by dandevri** [comment]
👋 Hi Robert,

Looking good! How did it go?

**Comment by robert-hoekstra** [comment]
Tutorial was fairly easy to use. However I found it a bit strange to commit and make pull requests to 'myself' I think that working in a team will clarify this a bit.
