### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by marissaverdonck** [cmda-bt/pt-course-18-19#81]
# Octocat

## Name
Marissa Verdonck

## Class
Tech 4

## GitHub username
https://github.com/marissaverdonck

## I Closed PR
https://github.com/marissaverdonck/github-slideshow/pull/3

## II GitHub Pages
https://marissaverdonck.github.io/github-pages-with-jekyll/

**Comment by dandevri** [comment]
👋 Hi Marissa,

Looking good! How did it go?
