### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by lennartdeknikker** [cmda-bt/pt-course-18-19#82]
# My Introduction
I'm a second year student, momentarily working towards becoming a better web developer.

## Name
Lennart de Knikker

## Class
212

## About me
Find out more on lenn4rt.com

## Goals
Getting better at JS and working with frameworks like Angular, Vue and React

## Skill level
Intermediate

## GitHub username
https://github.com/lennartdeknikker

## GitHub repository
https://github.com/lennartdeknikker/pt-course-18-19

**Comment by dandevri** [comment]
👋  Lennart, I've added your wiki to our _project-tech_ admin sheet!
