### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by robert-hoekstra** [cmda-bt/pt-course-18-19#83]
# Run

## Name
Robert Hoekstra

## Class
214 (Tech 3)

## GitHub username
robert-hoekstra

## Code
cm9iZXJ0LWhvZWtzdHJhCg==

**Comment by dandevri** [comment]
Achievement unlocked 🏆 

How was working with the `cli`?

**Comment by robert-hoekstra** [comment]
The tutorial was quite easy. However I am not familiar enough to work with the terminal all the time. Practice makes perfect I guess?
