### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by TomasStolp** [cmda-bt/pt-course-18-19#88]
# My Introduction

## Name
Tomas Stolp

## Class
Tech 3

## About me
Intermediate in coding and programming. Lots left to learn.
Love metal, Punk & reggae music!

## Goals
Getting the concept of progressive enhancement and apply it.
Improve JS skills.
Learn the principles of Node.js.
Getting deeper in the backend, CLI. etc.
Working with GIT & GITHub.

## Skill level
**Intermediate**. I have a lot to offer, but still lots left to learn.
No experience in Node.js yet.

## GitHub username
TomasS666

## GitHub repository
https://github.com/TomasS666/Project-tech

**Comment by dandevri** [comment]
👋  Tomas, I've added your wiki to our project-tech admin sheet!
