### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by lennartdeknikker** [cmda-bt/pt-course-18-19#89]
# Octocat

## Name
Lennart de Knikker

## Class
212

## GitHub username
https://github.com/lennartdeknikker

## Links
https://github.com/lennartdeknikker/github-slideshow

## Feedback
I already did those assignments 3 months ago, so I don't still have the PR, but I can work with git just fine now.

![image](https://user-images.githubusercontent.com/45396678/57483464-34a76000-72a7-11e9-8ad7-080f1562ca33.png)

**Comment by dandevri** [comment]
Looking good Lennart!
