### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by StefanGerrits2** [cmda-bt/pt-course-18-19#9]
# My Introduction

## Name
`Stefan Gerrits`

## Class
`211 - Tech - 1`

## About me
`I am 18 years old`

## Goals
`To learn more about Backend- and Frontend Development`

## Skill level
`Beginner`

## GitHub username
[https://github.com/StefanGerrits2](url)

## GitHub repository
[https://github.com/StefanGerrits2/datingwebsite-bloktech](url)

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
