### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by jor-s** [cmda-bt/pt-course-18-19#91]
# My Introduction

## Name
Jordy Sahit

## Class
214/Tech-4

## About me
Ik vind het wel leuk om wat te powerliften.

## Goals
Na dit project Javascript beter begrijpen en kunnen programmeren.

## Skill level
Beginner

## GitHub username
https://github.com/sahitj001

## GitHub repository
https://github.com/sahitj001/tech

**Comment by dandevri** [comment]
👋 Jordy, I've added your wiki to our project-tech admin sheet!
