### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by benl95** [cmda-bt/pt-course-18-19#97]
# My Introduction

CMD Student aan de Hogeschool van Amsterdam

## Name
Ben Langenberg

## Class
Tech 3

## About me
Mijn naam is Ben, 23 jaar en woonachtig in Zaandam.

## Goals
De basis goed onder de knie krijgen en ook kunnen toepassen in de praktijk

## Skill level
Beginner, de enige skills die ik heb zijn degene die ik heb geleerd op CMD. 

## GitHub username
https://github.com/benl95

## GitHub repository
https://github.com/benl95/Project-Tech.git

**Comment by dandevri** [comment]
Thanks! Your link has been added to the Admin sheet! 🎉
